version: '3.9'

services:

  mongodb:
    image: mongo:6.0
    container_name: mongo_notification
    hostname: mongo
    restart: unless-stopped
    ports:
      - ${MONGO_HOST_PORT}:27017
    volumes:
      - $MONGO_DATA_HOST_PATH:/var/lib/mongodb/_data/
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb/
      - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    networks:
      - ${NETWORK_NAME}
    command: ["--bind_ip", "0.0.0.0"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    depends_on:
      - mongodb
    ports:
      - ${SERVER_HOST_PORT}:8080
    volumes:
      - /app/docker/notifications:/var/lib/mongodb/_data/
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILE
      - SPRING_APPLICATION_NAME=$APP_NAME
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=$MONGO_DB
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=$MONGO_AUTO_INDEX_CREATION
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=$MONGO_HOST_PORT
      - SPRING_DATA_MONGODB_USERNAME=$MONGO_DB_USERNAME
      - SPRING_DATA_MONGODB_PASSWORD=$MONGO_DB_PASSWORD
      - SPRING_DATA_MONGODB_DATABASE=$MONGO_DB
    networks:
      - ${NETWORK_NAME}

networks:
  ovnny_network-001:
    driver: bridge
