FROM mongo:6.0

ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=root

COPY create-user.sh /docker-entrypoint-initdb.d
RUN chmod +x /docker-entrypoint-initdb.d/create-user.sh

EXPOSE '27017'

CMD ["mongod"]